# Generated by Django 4.2.20 on 2025-05-13 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utls.func


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassRooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        default=utls.func.generator, max_length=255, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "class_type",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("capacity", models.IntegerField(blank=True, null=True)),
                (
                    "access_type",
                    models.CharField(
                        choices=[("email", "Email"), ("password", "Password")],
                        max_length=255,
                    ),
                ),
                ("start_join_date", models.DateTimeField(blank=True, null=True)),
                ("end_join_date", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ManyToManyField(
                        blank=True,
                        related_name="classrooms_as_mentor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ManyToManyField(
                        related_name="classrooms_as_teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="class_app.classrooms",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ManyToManyField(
                        blank=True,
                        related_name="classrooms_as_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
