# Generated by Django 4.2.20 on 2026-01-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
